/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/activity/Allposts': RouteRecordInfo<'/activity/Allposts', '/activity/Allposts', Record<never, never>, Record<never, never>>,
    '/activity/Create': RouteRecordInfo<'/activity/Create', '/activity/Create', Record<never, never>, Record<never, never>>,
    '/activity/Edit': RouteRecordInfo<'/activity/Edit', '/activity/Edit', Record<never, never>, Record<never, never>>,
    '/activity/Profile': RouteRecordInfo<'/activity/Profile', '/activity/Profile', Record<never, never>, Record<never, never>>,
    '/activity/Workouts': RouteRecordInfo<'/activity/Workouts', '/activity/Workouts', Record<never, never>, Record<never, never>>,
    '/Admin': RouteRecordInfo<'/Admin', '/Admin', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Progress': RouteRecordInfo<'/Progress', '/Progress', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/Stats': RouteRecordInfo<'/Stats', '/Stats', Record<never, never>, Record<never, never>>,
  }
}
