GET http://localhost:3000/api/v1/posts/

###
GET http://localhost:3000/api/v1/posts/1
###

GET http://localhost:3000/api/v1/posts/userid/1
###
DELETE http://localhost:3000/api/v1/posts/1
###
POST http://localhost:3000/api/v1/posts
Content-Type: application/json

{
      "firstName": "Admin",
      "lastName": "Admin",
      "username": "admin",
      "postType": "Cardio",
      "calories": 100,
      "date": "1 January 2020",
      "record": 100,
      "unit" : "Minutes",
      "caption": "Test",
      "userid": 1
}

###
PATCH http://localhost:3000/api/v1/posts/1
Content-Type: application/json

{
      "firstName": "Admin",
      "lastName": "Admin",
      "username": "admin",
      "postType": "Cardio",
      "calories": 110,
      "date": "1 January 2020",
      "record": 200,
      "unit" : "Minutes",
      "caption": "Test 3",
      "photo" : "../assets/genericphoto.jpg",
      "postid" : 2,
      "userid": 1
}
###
GET http://localhost:3000/api/v1/posts

###
GET http://localhost:3000/api/v1/users/

###
GET http://localhost:3000/api/v1/users/2

###
PATCH http://localhost:3000/api/v1/users/2

Content-Type: application/json
      {
      "firstname": "John",
      "lastname": "Doe",
      "email": "jdoe@example.com",
      "username": "jdoe",
      "password": "jd",
      "userid" : 2,
      "isadmin": false,
      "bio": "Test Update",
      "followers": 123,
      "following": 321,
      "posts": 0,
      "statsToday": {
        "maxlift": 200,
        "maxtime": "2:00",
        "maxdist": 5,
        "maxcal": 500
      },
      "statsAll": {
        "maxlift": 250,
        "maxtime": "10:00",
        "maxdist": 30,
        "maxcal": 5000
      }
      
    }

###
DELETE http://localhost:3000/api/v1/users/5

###
POST http://localhost:3000/api/v1/users/
Content-Type: application/json

{
      "firstname": "Admin",
      "lastname": "User",
      "email": ""
}

###
PATCH  http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
      "password": "admin"
}

###
POST http://localhost:3000/api/v1/workout/
Content-Type: application/json

{
      "userid": 1,
      "exercise_name": "Bench Press",
      "type": "Strength",
      "date": "01 January 2024",
      "record": 175,
      "unit" : "Pounds",
      "count": 5
}

###

